version: "3.8"
services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

      MONGO_INITDB_DATABASE: chats
      MONGO_INITDB_USERNAME: appuser
      MONGO_INITDB_PASSWORD: apppassword

    volumes:
      - mongo-data:/data/db
  
  api:
    build:
      context: .
      dockerfile: builds/api/Dockerfile
    container_name: api
    ports:
      - "8000:8000"
  
  ingestion:
    build:
      context: .
      dockerfile: builds/twitch_data_ingestor/Dockerfile
    container_name: twitch_data_ingestor
    command: tail -f /dev/null
    volumes:
      - ./.env:/app/.env
    

volumes:
  mongo-data:
